// Package report generates audit output in multiple formats:
// JSON, Markdown, and SARIF 2.1.0.
package report

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/codeaudit/codeaudit/pkg/types"
)

// Format controls the output format.
type Format string

const (
	FormatJSON     Format = "json"
	FormatMarkdown Format = "markdown"
	FormatSARIF    Format = "sarif"
	FormatText     Format = "text"
)

// Generator produces audit reports.
type Generator struct{}

// New creates a new report generator.
func New() *Generator { return &Generator{} }

// Write writes the result in the given format to outPath.
// If outPath is "-", it writes to stdout.
func (g *Generator) Write(result *types.AuditResult, format Format, outPath string) error {
	var content string
	var err error

	switch format {
	case FormatJSON:
		content, err = g.toJSON(result)
	case FormatMarkdown:
		content, err = g.toMarkdown(result)
	case FormatSARIF:
		content, err = g.toSARIF(result)
	case FormatText:
		content, err = g.toText(result)
	default:
		return fmt.Errorf("unknown format: %s", format)
	}
	if err != nil {
		return err
	}

	if outPath == "-" || outPath == "" {
		fmt.Print(content)
		return nil
	}
	return os.WriteFile(outPath, []byte(content), 0644)
}

// ---- JSON ----------------------------------------------------------------

func (g *Generator) toJSON(result *types.AuditResult) (string, error) {
	b, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// ---- Markdown ------------------------------------------------------------

var markdownTmpl = `# CodeAudit Security Report

**Target:** {{ .Target.Path }}
**Scan Date:** {{ .StartTime.Format "2006-01-02 15:04:05" }}
**Duration:** {{ .Duration }}

---

## Executive Summary

| Severity | Count |
|----------|-------|
| 🔴 CRITICAL | {{ index .Summary.BySeverity "CRITICAL" }} |
| 🟠 HIGH     | {{ index .Summary.BySeverity "HIGH" }} |
| 🟡 MEDIUM   | {{ index .Summary.BySeverity "MEDIUM" }} |
| 🟢 LOW      | {{ index .Summary.BySeverity "LOW" }} |
| ℹ️ INFO     | {{ index .Summary.BySeverity "INFO" }} |

**Total Findings:** {{ .Summary.TotalFindings }}
**Risk Score:** {{ printf "%.1f" .Summary.RiskScore }}

---

## Agent Summary

| Agent | Findings |
|-------|---------|
{{ range $agent, $count := .Summary.ByAgent -}}
| {{ $agent }} | {{ $count }} |
{{ end }}

---

## Findings

{{ range .Findings }}
### [{{ .Severity }}] {{ .Title }}

- **File:** ` + "`" + `{{ .FilePath }}{{ if .Line }}:{{ .Line }}{{ end }}` + "`" + `
- **Agent:** {{ .AgentID }}
- **Rule:** {{ .RuleID }}
- **Confidence:** {{ printf "%.0f%%" (mul .Confidence 100.0) }}

**Description:**
{{ .Description }}

{{ if .CodeSnippet -}}
**Code:**
` + "```go\n{{ .CodeSnippet }}\n```" + `
{{ end -}}

**Suggestion:**
{{ .Suggestion }}

{{ if .References -}}
**References:** {{ join .References ", " }}
{{ end -}}

---
{{ end }}

*Generated by [CodeAudit](https://github.com/codeaudit/codeaudit) at {{ .EndTime.Format "2006-01-02 15:04:05 UTC" }}*
`

func (g *Generator) toMarkdown(result *types.AuditResult) (string, error) {
	// Pre-sort by severity weight.
	sortFindings(result.Findings)

	funcMap := template.FuncMap{
		"join": strings.Join,
		"mul":  func(a, b float64) float64 { return a * b },
	}

	tmpl, err := template.New("report").Funcs(funcMap).Parse(markdownTmpl)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	if err := tmpl.Execute(&sb, result); err != nil {
		return "", err
	}
	return sb.String(), nil
}

// ---- Text (terminal) -----------------------------------------------------

func (g *Generator) toText(result *types.AuditResult) (string, error) {
	sortFindings(result.Findings)
	var sb strings.Builder

	sb.WriteString("\n╔══════════════════════════════════════════════════════════╗\n")
	sb.WriteString("║          CodeAudit — Security Audit Report                ║\n")
	sb.WriteString("╚══════════════════════════════════════════════════════════╝\n\n")

	sb.WriteString(fmt.Sprintf("Target  : %s\n", result.Target.Path))
	sb.WriteString(fmt.Sprintf("Date    : %s\n", result.StartTime.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("Duration: %s\n\n", result.Duration))

	sb.WriteString("── Summary ─────────────────────────────────────────────────\n")
	sb.WriteString(fmt.Sprintf("  CRITICAL : %d\n", result.Summary.BySeverity["CRITICAL"]))
	sb.WriteString(fmt.Sprintf("  HIGH     : %d\n", result.Summary.BySeverity["HIGH"]))
	sb.WriteString(fmt.Sprintf("  MEDIUM   : %d\n", result.Summary.BySeverity["MEDIUM"]))
	sb.WriteString(fmt.Sprintf("  LOW      : %d\n", result.Summary.BySeverity["LOW"]))
	sb.WriteString(fmt.Sprintf("  INFO     : %d\n", result.Summary.BySeverity["INFO"]))
	sb.WriteString(fmt.Sprintf("  Total    : %d  (Risk Score: %.1f)\n\n", result.Summary.TotalFindings, result.Summary.RiskScore))

	sb.WriteString("── Findings ─────────────────────────────────────────────────\n")
	for i, f := range result.Findings {
		sb.WriteString(fmt.Sprintf("\n[%d] %s  [%s]\n", i+1, f.Title, f.Severity))
		sb.WriteString(fmt.Sprintf("    File   : %s", f.FilePath))
		if f.Line > 0 {
			sb.WriteString(fmt.Sprintf(":%d", f.Line))
		}
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("    Agent  : %s\n", f.AgentID))
		sb.WriteString(fmt.Sprintf("    Rule   : %s\n", f.RuleID))
		sb.WriteString(fmt.Sprintf("    Desc   : %s\n", f.Description))
		if f.Suggestion != "" {
			sb.WriteString(fmt.Sprintf("    Fix    : %s\n", f.Suggestion))
		}
	}

	sb.WriteString("\n────────────────────────────────────────────────────────────\n")
	return sb.String(), nil
}

// ---- SARIF 2.1.0 ---------------------------------------------------------

type sarifLog struct {
	Version string      `json:"version"`
	Schema  string      `json:"$schema"`
	Runs    []sarifRun  `json:"runs"`
}

type sarifRun struct {
	Tool    sarifTool    `json:"tool"`
	Results []sarifResult `json:"results"`
	Artifacts []sarifArtifact `json:"artifacts,omitempty"`
}

type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}

type sarifDriver struct {
	Name            string      `json:"name"`
	Version         string      `json:"version"`
	InformationURI  string      `json:"informationUri"`
	Rules           []sarifRule `json:"rules"`
}

type sarifRule struct {
	ID               string          `json:"id"`
	Name             string          `json:"name"`
	ShortDescription sarifText       `json:"shortDescription"`
	FullDescription  sarifText       `json:"fullDescription"`
	Properties       sarifProperties `json:"properties"`
}

type sarifText struct {
	Text string `json:"text"`
}

type sarifProperties struct {
	Tags     []string `json:"tags,omitempty"`
	Severity string   `json:"security-severity,omitempty"`
}

type sarifResult struct {
	RuleID    string           `json:"ruleId"`
	Level     string           `json:"level"`
	Message   sarifText        `json:"message"`
	Locations []sarifLocation  `json:"locations"`
}

type sarifLocation struct {
	PhysicalLocation sarifPhysical `json:"physicalLocation"`
}

type sarifPhysical struct {
	ArtifactLocation sarifArtifactRef `json:"artifactLocation"`
	Region           sarifRegion      `json:"region"`
}

type sarifArtifactRef struct {
	URI string `json:"uri"`
}

type sarifRegion struct {
	StartLine int `json:"startLine"`
}

type sarifArtifact struct {
	Location sarifArtifactRef `json:"location"`
}

func (g *Generator) toSARIF(result *types.AuditResult) (string, error) {
	ruleMap := make(map[string]sarifRule)
	var results []sarifResult

	for _, f := range result.Findings {
		ruleID := f.RuleID
		if ruleID == "" {
			ruleID = f.AgentID + "/" + f.Title
		}
		if _, ok := ruleMap[ruleID]; !ok {
			ruleMap[ruleID] = sarifRule{
				ID:               ruleID,
				Name:             f.Title,
				ShortDescription: sarifText{Text: f.Title},
				FullDescription:  sarifText{Text: f.Description},
				Properties: sarifProperties{
					Severity: severityToNumeric(f.Severity),
				},
			}
		}

		results = append(results, sarifResult{
			RuleID: ruleID,
			Level:  severityToSARIFLevel(f.Severity),
			Message: sarifText{Text: f.Description + " " + f.Suggestion},
			Locations: []sarifLocation{{
				PhysicalLocation: sarifPhysical{
					ArtifactLocation: sarifArtifactRef{URI: f.FilePath},
					Region:           sarifRegion{StartLine: maxInt(f.Line, 1)},
				},
			}},
		})
	}

	var rules []sarifRule
	for _, r := range ruleMap {
		rules = append(rules, r)
	}

	log := sarifLog{
		Version: "2.1.0",
		Schema:  "https://json.schemastore.org/sarif-2.1.0.json",
		Runs: []sarifRun{{
			Tool: sarifTool{
				Driver: sarifDriver{
					Name:           "CodeAudit",
					Version:        "1.0.0",
					InformationURI: "https://github.com/codeaudit/codeaudit",
					Rules:          rules,
				},
			},
			Results: results,
		}},
	}

	b, err := json.MarshalIndent(log, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// ---- helpers -------------------------------------------------------------

func severityToSARIFLevel(s types.Severity) string {
	switch s {
	case types.SeverityCritical, types.SeverityHigh:
		return "error"
	case types.SeverityMedium:
		return "warning"
	case types.SeverityLow:
		return "note"
	default:
		return "none"
	}
}

func severityToNumeric(s types.Severity) string {
	switch s {
	case types.SeverityCritical:
		return "9.8"
	case types.SeverityHigh:
		return "7.5"
	case types.SeverityMedium:
		return "5.0"
	case types.SeverityLow:
		return "2.0"
	default:
		return "0.0"
	}
}

var severityOrder = map[types.Severity]int{
	types.SeverityCritical: 0,
	types.SeverityHigh:     1,
	types.SeverityMedium:   2,
	types.SeverityLow:      3,
	types.SeverityInfo:     4,
}

func sortFindings(findings []*types.Finding) {
	sort.Slice(findings, func(i, j int) bool {
		oi := severityOrder[findings[i].Severity]
		oj := severityOrder[findings[j].Severity]
		if oi != oj {
			return oi < oj
		}
		return findings[i].FilePath < findings[j].FilePath
	})
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
